### ISSUE TITLE
Create Schema (model) - User

### ISSUE THREAD

**Issue by davideastmond** [chingu-voyages/v36-bears-team-14#24]
- Properties such as - name, e-mail

**Comment by TyreKing** [comment]
Properties:
_Id | AutoGenerated

First name 
Last name 
User name 
Password
Description/Bio ~? Maybe add this?
Recipes

**Comment by davideastmond** [comment]
Hey I created a section in out Figma called "Data models" and copied the two models over to there and added types. I also put some comments on there. LMK what you think. Re: storing images - I'm thinking maybe we should explore an API that allows us to upload / retrieve images? Then we can store the images as urls(strings) in the DB. 🤔
