### ISSUE TITLE
- Create Recipes Model

### ISSUE THREAD

**Issue by davideastmond** [chingu-voyages/v36-bears-team-14#25]
- Various properties for recipes

**Comment by TyreKing** [comment]
_id | AutoGenerated

Name 
Description 
Likes
Users ~? May not need (Created By)
Images  ~! Need to discuss : _https://www.mongodb.com/community/forums/t/process-of-storing-images-in-mongodb/15093_
Date Created

**Comment by MarilynPapadopoulos** [comment]
Recipe: {
_id: ObjectId,
name: String,
description: String,
likes: { ...userId: Date },
postedByUser: String(user’s _id),
images: [url: string]
timeStamp
}
