### ISSUE TITLE
[API] Implement authentication

### ISSUE THREAD

**Issue by davideastmond** [chingu-voyages/v36-bears-team-14#29]
Create authentication route and logic.
POST /api/authentication/logout (terminates the session)
POST /api/authentication/local/register - Create a new user
POST /api/authentication (assigns a session (log in))
- User name and password
- bcryptjs to hash passwords
- Cookie sessions

**Comment by TyreKing** [comment]
bcrypt is fine for hashing.
I would be fine with just using JWT.  As for storing the JWT, here is a good link: https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage
